# Generated by Django 5.2.15 on 2026-06-29 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('trigger_type', models.CharField(choices=[('sos_button', 'Botón SOS (app)'), ('fall_detection', 'Detección de caída (wearable)'), ('crash_detection', 'Detección de choque (vehículo)'), ('biometric', 'Sensores biométricos'), ('voice', 'Asistente de voz'), ('manual', 'Carga manual')], default='sos_button', max_length=20)),
                ('event_type', models.CharField(choices=[('cardiac', 'Paro / dolor cardíaco'), ('stroke', 'ACV / sospecha de ACV'), ('trauma', 'Trauma grave'), ('vehicle', 'Accidente vehicular'), ('fall', 'Caída'), ('unconscious', 'Pérdida de conciencia'), ('respiratory', 'Dificultad respiratoria'), ('allergic', 'Reacción alérgica'), ('other', 'Otro')], default='other', max_length=14)),
                ('severity', models.IntegerField(default=3, help_text='1 = crítico … 5 = leve (escala tipo ESI)')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('location_desc', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('country', models.CharField(default='Argentina', max_length=80)),
                ('provider_distance_km', models.FloatField(blank=True, null=True)),
                ('ambulance_eta_min', models.IntegerField(blank=True, null=True)),
                ('decision_score', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Orquestando'), ('en_route', 'Ambulancia en camino'), ('arrived', 'Paciente ingresado'), ('resolved', 'Resuelto'), ('cancelled', 'Cancelado')], default='active', max_length=10)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('country', models.CharField(default='Argentina', max_length=60)),
                ('international', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('?', 'Desconocido')], default='?', max_length=3)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('languages', models.CharField(default='Español', help_text='Idiomas separados por coma', max_length=120)),
                ('home_address', models.CharField(blank=True, max_length=200)),
                ('home_city', models.CharField(blank=True, max_length=80)),
                ('home_country', models.CharField(default='Argentina', max_length=80)),
                ('home_lat', models.FloatField(default=-34.6037)),
                ('home_lng', models.FloatField(default=-58.3816)),
                ('notes', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Perfil principal mostrado por defecto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_primary', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('icon', models.CharField(blank=True, max_length=8)),
            ],
            options={
                'verbose_name_plural': 'specialties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=24)),
                ('icon', models.CharField(blank=True, max_length=8)),
                ('title', models.CharField(max_length=120)),
                ('detail', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('done', 'Completado'), ('active', 'En curso'), ('pending', 'Pendiente')], default='done', max_length=8)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.emergencyevent')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('dose', models.CharField(blank=True, max_length=80)),
                ('frequency', models.CharField(blank=True, max_length=80)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='core.patientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('severity', models.CharField(choices=[('low', 'Leve'), ('medium', 'Moderada'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='core.patientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(blank=True, max_length=80)),
                ('member_id', models.CharField(blank=True, max_length=80)),
                ('coverage_level', models.CharField(choices=[('basic', 'Básica'), ('full', 'Completa'), ('premium', 'Premium')], default='full', max_length=10)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('international', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='core.insurancenetwork')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='core.patientprofile')),
            ],
            options={
                'ordering': ['-active', 'network__name'],
            },
        ),
        migrations.AddField(
            model_name='emergencyevent',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.patientprofile'),
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('relationship', models.CharField(blank=True, max_length=60)),
                ('phone', models.CharField(max_length=40)),
                ('is_primary', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.patientprofile')),
            ],
            options={
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substance', models.CharField(max_length=120)),
                ('reaction', models.CharField(blank=True, max_length=200)),
                ('severity', models.CharField(choices=[('low', 'Leve'), ('medium', 'Moderada'), ('high', 'Alta'), ('anaphylaxis', 'Anafilaxia')], default='medium', max_length=12)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='core.patientprofile')),
            ],
            options={
                'verbose_name_plural': 'allergies',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('kind', models.CharField(choices=[('hospital', 'Hospital general'), ('clinic', 'Clínica'), ('trauma', 'Centro de trauma'), ('cardiac', 'Centro cardiovascular'), ('stroke', 'Centro de ACV'), ('pediatric', 'Hospital pediátrico')], default='hospital', max_length=12)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('country', models.CharField(default='Argentina', max_length=80)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('languages', models.CharField(default='Español', max_length=160)),
                ('quality_rating', models.FloatField(default=4.0, help_text='0–5')),
                ('trauma_level', models.IntegerField(default=0, help_text='0 = ninguno, 1–3 = nivel de trauma')),
                ('er_open', models.BooleanField(default=True, help_text='Guardia activa 24/7')),
                ('total_beds', models.IntegerField(default=20)),
                ('available_beds', models.IntegerField(default=5)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('accepted_networks', models.ManyToManyField(blank=True, related_name='providers', to='core.insurancenetwork')),
                ('specialties', models.ManyToManyField(blank=True, related_name='providers', to='core.specialty')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='emergencyevent',
            name='selected_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.provider'),
        ),
        migrations.CreateModel(
            name='ProviderCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.FloatField(default=0)),
                ('eta_min', models.IntegerField(default=0)),
                ('score', models.FloatField(default=0)),
                ('breakdown_json', models.TextField(blank=True, help_text='JSON con el desglose del puntaje')),
                ('selected', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='core.emergencyevent')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidacies', to='core.provider')),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
        migrations.AddField(
            model_name='emergencyevent',
            name='required_specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.specialty'),
        ),
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_city', models.CharField(max_length=80)),
                ('destination_country', models.CharField(max_length=80)),
                ('destination_lat', models.FloatField()),
                ('destination_lng', models.FloatField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ready', 'Listo'), ('draft', 'Borrador')], default='ready', max_length=8)),
                ('risk_level', models.CharField(default='Moderado', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('data_json', models.TextField(blank=True, help_text='JSON: riesgos, prestadores, idioma, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_plans', to='core.patientprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
